/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-03 08:47:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.criminal_record_management.entities.Users;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.criminal_record_management.entities.Users");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Crime Records Management System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Added CSS for Login and Register links */\r\n");
      out.write("        .user-auth a:hover {\r\n");
      out.write("            color: blue !important;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head> \r\n");
      out.write("<body>\r\n");
 Users u =(Users) session.getAttribute("currentUser"); 
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Seal_of_Karnataka.svg/800px-Seal_of_Karnataka.svg.png\" alt=\"CRMS Logo\" width=\"90\" height=\"80\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\" style=\"text-decoration: none; color: white ; padding: 10px 20px; transition: all 0.3s ease;\" onmouseover=\"this.style.backgroundColor='lightgray'; this.style.borderRadius='5px'; this.style.boxShadow='0 0 5px rgba(0, 0, 0, 0.2)'\" onmouseout=\"this.style.backgroundColor=''; this.style.borderRadius=''; this.style.boxShadow=''\">Home</a></li>\r\n");
      out.write("                <!-- Updated link for \"Crimes\" to point to crimes.html -->\r\n");
      out.write("                <li><a href=\"crimes.jsp\" style=\"text-decoration: none; color: white; padding: 10px 20px; transition: all 0.3s ease;\" onmouseover=\"this.style.backgroundColor='lightgray'; this.style.borderRadius='5px'; this.style.boxShadow='0 0 5px rgba(0, 0, 0, 0.2)'\" onmouseout=\"this.style.backgroundColor=''; this.style.borderRadius=''; this.style.boxShadow=''\">Crimes</a></li>\r\n");
      out.write("                <li><a href=\"fir.jsp\" style=\"text-decoration: none; color: white; padding: 10px 20px; transition: all 0.3s ease;\" onmouseover=\"this.style.backgroundColor='lightgray'; this.style.borderRadius='5px'; this.style.boxShadow='0 0 5px rgba(0, 0, 0, 0.2)'\" onmouseout=\"this.style.backgroundColor=''; this.style.borderRadius=''; this.style.boxShadow=''\">FIRs</a></li>\r\n");
      out.write("                <li><a href=\"criminals.jsp\" style=\"text-decoration: none; color: white; padding: 10px 20px; transition: all 0.3s ease;\" onmouseover=\"this.style.backgroundColor='lightgray'; this.style.borderRadius='5px'; this.style.boxShadow='0 0 5px rgba(0, 0, 0, 0.2)'\" onmouseout=\"this.style.backgroundColor=''; this.style.borderRadius=''; this.style.boxShadow=''\">Criminals</a></li>\r\n");
      out.write("                <li><a href=\"complaints.jsp\" style=\"text-decoration: none; color: white; padding: 10px 20px; transition: all 0.3s ease;\" onmouseover=\"this.style.backgroundColor='lightgray'; this.style.borderRadius='5px'; this.style.boxShadow='0 0 5px rgba(0, 0, 0, 0.2)'\" onmouseout=\"this.style.backgroundColor=''; this.style.borderRadius=''; this.style.boxShadow=''\">Complaints</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"user-auth\">\r\n");
      out.write("            <a href=\"");
      out.print( (u != null) ? "logout.jsp" : "login.jsp" );
      out.write('"');
      out.write('>');
      out.print( (u != null) ? "Logout" : "Login" );
      out.write("</a> / <a href=\"register.jsp\">Register</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main>\r\n");
      out.write("        <!-- Bootstrap Carousel -->\r\n");
      out.write("        <div id=\"carouselExampleControls\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img src=\"https://lifebeyondnumbers.b-cdn.net/wp-content/uploads/2019/01/National-Emblem-of-India.jpg\" class=\"d-block w-100\" alt=\"Image 1\" width=\"150\" height=\"510\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"https://static.vecteezy.com/system/resources/thumbnails/022/596/287/small/judge-gavel-with-justice-lawyers-having-team-meeting-at-law-firm-in-background-concepts-of-law-generative-ai-photo.jpg\" class=\"d-block w-100\" alt=\"Image 2\" width=\"150\" height=\"510\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bGF3fGVufDB8fDB8fHww\" class=\"d-block w-100\" alt=\"Image 3\" width=\"150\" height=\"510\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"carousel-control-prev\" href=\"#carouselExampleControls\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"sr-only\">Previous</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"carousel-control-next\" href=\"#carouselExampleControls\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"sr-only\">Next</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"banner\">\r\n");
      out.write("            <marquee><h1>Welcome to the Crime Records Management System</h1></marquee>\r\n");
      out.write("            <p>Keep track of crimes, FIRs, criminals, and complaints.</p>\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Get Started</a>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"contact-info\">\r\n");
      out.write("            <p>Contact us: info@crms.com</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"legal\">\r\n");
      out.write("            <a href=\"#\">Terms of Service</a> | <a href=\"#\">Privacy Policy</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"legal\">\r\n");
      out.write("            <a href=\"#\">About Us</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
